baseURL = "https://ghsable.github.io/sunalog/"
languageCode = "en-us"
title = "sunalog"
publishDir = "docs"
googleAnalytics = "UA-157767797-1"
theme = "github-style"
copyright = "Copyright© 2019 <a href=\"https://ghsable.github.io/sunalog/about/\">@suna</a> All Rights Reserved."

[Params]
 author = "suna"
 description = "Use software leverage to your advantage."
 github = "ghsable"
 twitter = "tnsable"
 email = "suna@xmpp.is"
 utterances = "ghsable/sunalog"
 url = "https://ghsable.github.io"
 avatar = 'https://raw.githubusercontent.com/ghsable/sunalog/master/images/shima.jpg'
