baseURL = "https://ghsable.github.io/sunalog/"
languageCode = "en-us"
title = "sunalog"
theme = "github-style"
publishDir = "docs"
googleAnalytics = ""

[Params]
 author = "suna"
 description = "Use software leverage to your advantage."
 github = "ghsable"
 twitter = "tnsable"
 email = "suna@xmpp.is"
 utterances = "https://github.com/ghsable/ghsable.github.io"
 avatar = 'images/avatar.png'
 url = "https://github.com/ghsable/ghsable.github.io"
