baseURL = "https://ghsable.github.io/sunalog/"
languageCode = "en-us"
title = "sunalog"
theme = "github-style"
publishDir = "docs"
copyright = "Copyright© 2019 <a href=\"https://github.com/ghsable/sunalog\">@sunalog</a> All Rights Reserved."
googleAnalytics = "UA-157767797-1"
utterances = "https://ghsable.github.io/sunalog"
disqusShortname = "sunalog"

[Params]
 author = "suna"
 description = "Use software leverage to your advantage."
 github = "ghsable"
 twitter = "tnsable"
 email = "suna@xmpp.is"
 url = "https://ghsable.github.io"
 utterances = "https://ghsable.github.io"
 avatar = 'https://ghsable.github.io/sunalog/images/shima.jpg'
