baseURL = "https://ghsable.github.io/sunalog/"
canonifyurls = true
languageCode = "en-us"
title = "sunalog"
googleAnalytics = ""
theme = "github-style"

[Params]
 author = "suna"
 description = "Use software leverage to your advantage."
 github = "ghsable"
 twitter = "tnsable"
 email = "suna@xmpp.is"
 utterances = "https://github.com/ghsable/ghsable.github.io"
 avatar = 'image/theme/profile.jpg'

