backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

locale: "ja"                          # 表示言語
media_folder: "static/images/uploads" # 画像保存先(レポジトリ'/'起点)
public_folder: "images/uploads"       # 画像保存先(デプロイ先'/'起点)
publish_mode: editorial_workflow      # 記事ステータス表示

collections: # A list of collections the CMS should be able to edit
  - name: "posts"                               # セクション名
    label: "Posts"                              # 表示用ラベル
    folder: "content/posts"                     # Push先
    create: true                                # 新規作成可否
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # ファイル名
    fields: # 入力項目
      - {label: "Title", name: "title", widget: "string"}
      # datetime - https://www.netlifycms.org/docs/widgets/datetime/
      - {label: "Publish Date", name: "date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm", format: "YYYY-MM-DDTHH:mm:ss+09:00", pickerUtc: false}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "content"
    label: "Content"
    folder: "content"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm", format: "YYYY-MM-DDTHH:mm:ss+09:00", pickerUtc: false}
      - {label: "Layout", name: "layout", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
