backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "images/uploads"
locale: "ja"

collections: # A list of collections the CMS should be able to edit
  - name: "post_2020" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post_2020" # Used in the UI, ie.: "New Post"
    folder: "content/posts/2020" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      #- {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
